---
title: "R Notebook"
output: html_notebook
---

```{r}
##THINGS WE SHOULD DO
#1. DO SOME EDA.
#2.ARBITRALRY LOOK AT A COUPLE COMPARISONS TO ADD CONTEXT. I,E LOOK AT A SPECIFIC ACTOR/ACTRESS AND COMPARE AND BE LIKE TOM CRUISE IS LIKELY TO MAKE 3X MORE MONEY THAN BRAD PITT OR SOMETHING.
#3 LOOK AT BY VARIOUS GROUPINGS, I,E STUIOS, ETC.
#SINCE THE METRIC IS LIFETIME GROSS, DOES IT MAKE SENSE TO DIVDE BY...# OF MOVIES? # OF YEARS, ETC ETC, TO GET AN AVERAGE.

```


```{r}
library(gbm)
library(pdp)
```

```{r}
df <- read.csv('final_action_v2.csv')
```

```{r}
head(df)
```

```{r}
sort(table(df$genres2), decreasing = TRUE)
```
```{r}
sort(table(df$studio), decreasing = TRUE)
```


```{r}
df <- subset(df, runtimeMinutes != "\\N") # remove wierd value
df$runtimeMinutes <-as.integer(df$runtimeMinutes) #convert to number
df$startYear <-as.integer(df$startYear) 
df$age <- 2023-df$startYear #age
df$lifetime_gross.scaled <- scale(df$lifetime_gross) #scale dependent variable
df$genres2 <- as.factor(df$genres2) #as factor
df$studio <- as.factor(df$studio) # as factor
df$profession1 <- as.factor(df$profession1)

# grouping various features

df$studio.grouped <- ifelse(df$studio == "WB", "WB",
                             ifelse(df$studio == "Fox", "Fox",
                                    ifelse(df$studio == "Uni.", "Uni.",
                                           ifelse(df$studio == "Par.", "Sony",
                                                  ifelse(df$studio == "MGM", "MGM", "other")))))
df$studio.grouped <- as.factor(df$studio.grouped)


df$genres2.grouped <- ifelse(df$genres2 == "Adventure", "Adventure",
                             ifelse(df$genres2 == "Crime", "Crime",
                                    ifelse(df$genres2 == "Comedy", "Comedy",
                                           ifelse(df$genres2 == "Sci-Fi", "Sci-Fi",
                                                  ifelse(df$genres2 == "Thriller", "Thriller", "Other")))))

df$genres2.grouped <- as.factor(df$genres2.grouped)

independent.vars <- c('isAdult', 'startYear', 'runtimeMinutes', 'studio.grouped','genres2.grouped', 'profession1')
dependent.vars <- c('lifetime_gross')
```

```{r}
head(df)
#model.data <- df[, subset]

```

```{r}
x <-df[, independent.vars]
y <- df[,dependent.vars]
```

```{r}
model <- gbm(y ~ ., data = x, distribution = "gaussian", n.trees = 50, interaction.depth = 3)
```

```{r}
summary(model)
```
```{r}
plot.gbm(model, i.var = "studio.grouped", n.trees = 50, type = "link")
```
```{r}
plot.gbm(model, i.var = "runtimeMinutes", n.trees = 50, type = "link")

```
```{r}
plot.gbm(model, i.var = "startYear", n.trees = 50, type = "link")

```
```{r}
plot.gbm(model, i.var = c("genres2.grouped", "studio.grouped"), n.trees = 50, type = "link")

```
```{r}
plot.gbm(model, i.var = c("genres2.grouped", "profession1"), n.trees = 50, type = "link")

```

